version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
      resource_class: medium
    steps: 
      - checkout
      - run: "docker network create testing-network"
      - run: "docker run --net testing-network --rm -d --name=httpecho mendhak/http-https-echo"
      - run: "docker build -t swift-async-http ."
      - run: "docker run --net testing-network --rm -e ECHO_IS_RUNNING=1 -e TESTING_HOST=httpecho -e TESTING_PORT=80 swift-async-http swift test"
workflows:
  test:
    jobs:
      - build
