version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
      resource_class: medium
    steps: 
      - checkout
      - install_echo:
          name: "Install Echo"
          command: "docker run --rm -d --name=http-echo -p 9001:80 mendhak/http-https-echo"
      - test_client:
          name: "Test Client"
          command: "docker build -t swift-async-http ."       
workflows:
  test:
    jobs:
      - build
